### ISSUE TITLE
Hay riesgos de ser demandados por Nintendo?

### ISSUE THREAD

**Issue by restrepotorres** [brayanramosc/pokedux#1]

**Comment by restrepotorres** [comment]
@brayanramosc plis responder rápido, temo por mi vida y la de mis familiares cercanos. u.u

**Comment by brayanramosc** [comment]
Hola estimado, es totalmente seguro su uso, pero si tocan a su puerta le aconsejo no abrir :v

**Comment by restrepotorres** [comment]
🙏🙏🙏
